config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  devise_for :users, layout: 'admin'

  namespace :admin do
    root 'menu_type_searches#index', as: 'root'
    resources :menu_type_searches, :menus, :restaurants, :cities
  end

  get 'scrape', to: 'scrapers#scrape'

  get 'search(/:action)', controller: 'search', action: :action, as: "search"

  resources :cities, :only => [:index, :create, :new]

  resources :cities, :path => '', :except => [:index, :create, :new]
  resources :cities, :path => '', :only => [] do
    resources :restaurants, :path => '', :except => [:index]
    resources :restaurants, :path => '', :only => [] do
      resources :menus, :path => '', :except => [:index]
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  extend FriendlyId

  has_many :restaurants

  friendly_id :name, use: :slugged

  validates :name, presence: true, uniqueness: { case_sensitive: false }

end

app/models/dish.rb
class Dish < ApplicationRecord
  has_many :ingredients, dependent: :destroy
  belongs_to :menu

  validates :name, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :dish

  validates :name, presence: true
end

app/models/menu.rb
class Menu < ApplicationRecord
  extend FriendlyId

  before_save :default_values

  has_many :dishes, dependent: :destroy
  belongs_to :restaurant
  belongs_to :menu_type

  friendly_id :name, use: :scoped, scope: :restaurant

  validates :name, presence: true, uniqueness: { scope: :restaurant_id, case_sensitive: false }

  private

  def default_values
    self.menu_type_id ||= 1
  end
end

app/models/menu_type.rb
class MenuType < ApplicationRecord
  has_many :menus
end

app/models/menu_type_search.rb
class MenuTypeSearch < ApplicationRecord
  before_save :default_values

  belongs_to :menu_type

  def self.find_type(type)
    find_or_create_by(searchable: type.downcase).menu_type
  end

  private

  def default_values
    self.menu_type_id ||= 1
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  extend FriendlyId
  dragonfly_accessor :image do
    default 'app/assets/images/uurwerker.png'
  end

  has_many :menus, dependent: :destroy
  belongs_to :city

  friendly_id :name, use: :scoped, scope: :city

  validates :name, presence: true, uniqueness: { scope: :city_id, case_sensitive: false }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/cities_controller.rb
class Admin::CitiesController < AdminController
  def index
    @cities = City.order(id: :asc)
  end

  def edit
    @city = City.friendly.find params[:id]
  end

  def update
    @city = City.friendly.find(params[:id]).update_attributes(clean_params)
    redirect_to admin_cities_path
  end

  def new
    @city = City.new
  end

  def create
    @city = City.create(clean_params)
    redirect_to admin_cities_path
  end

  def destroy
    City.friendly.find(params[:id]).destroy
    redirect_to admin_cities_path
  end

  private

  def clean_params
    params.require(:city).permit(:name)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  layout 'admin'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    admin_root_path
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all.includes(:restaurants)
  end

  def show
    @city = City.friendly.find(params[:id])
    @restaurants = @city.restaurants
  end

  private

  def clean_params
    params.require(:city).permit(:name)
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_restaurant, only: [:show]

  def show
    @menu = @restaurant.menus.friendly.find(params[:id])
    @dishes = @menu.dishes.order(id: :asc).includes(:ingredients).order('ingredients.id')
  end

  private

  def set_restaurant
    @restaurant = Restaurant.friendly.find(params[:restaurant_id])
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_city, only: [:show]

  def show
    @restaurant = @city.restaurants.friendly.find(params[:id])
    @menus = @restaurant.menus.order(id: :asc).includes(:menu_type)
  end

  private

  def set_city
    @city = City.friendly.find(params[:city_id])
  end

  def clean_params
    params.require(:restaurant).permit(:name)
  end
end

app/controllers/scrapers_controller.rb
class ScrapersController < ApplicationController

  def scrape
    render plain: 'hoi'
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def restaurants
    if clean_params[:q].empty?
      @restaurants = Restaurant.includes(:city).sample(50)
    else
      @restaurants = Restaurant.fuzzy_search(name: clean_params[:q]).includes(:city)
    end
  end

  def city_restaurants
    if clean_params[:q].empty?
      @restaurants = Restaurant.where(city_id: clean_params[:id]).includes(:city)
    else
      @restaurants = Restaurant.fuzzy_search(name: clean_params[:q]).where(city_id: clean_params[:id]).includes(:city)
    end
  end

  private

  def clean_params
    params.permit(
      q: Parameters.string,
      id: Parameters.integer
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/web_scraper_helper.rb
module WebScraperHelper
end

app/views/admin/cities/edit.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <%= bootstrap_form_for [:admin, @city] do |f| %>
      <%= f.text_field :name %>
      <%= f.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/admin/cities/index.html.erb
<div class="page-header">
  <h1>City's <small>[<%= link_to 'New', new_admin_city_path %>]</small></h1>
</div>

<table class="table table-striped">
  <thead>
    <th>#</th>
    <th>Name</th>
    <th>Slug</th>
    <th>Actions</th>
  </thead>
  <tbody>
    <% @cities.each do |city| %>
    <tr>
      <td><%= city.id %></td>
      <td><%= city.name %></td>
      <td><%= city.slug %></td>
      <td><%= link_to '[edit]', edit_admin_city_path(city) %> <%= link_to '[delete]', admin_city_path(city), method: 'delete' %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/cities/new.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <%= bootstrap_form_for [:admin, @city] do |f| %>
      <%= f.text_field :name %>
      <%= f.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/cities/index.html.erb
<header>
  <a href="<%= url_for(:root) %>" class="back">Back</a>
	<h1>Alle steden</h1>
</header>

<section id="restaurant-list">
  <ul>
    <% @cities.each do |city| %>
      <li>
        <h3 class="name"><%= link_to city.name, city %></h3>
        <hr><p><%= city.restaurants.size %> restaurants aanwezig</p>
      </li>
    <% end %>
  </ul>
</section>

app/views/cities/show.html.erb
<header>
  <a href="<%= url_for(:back) %>" class="back">Back</a>
	<h1><%= @city.name %></h1>
  <form action="/search/city_restaurants<%= @city.id %>" method="get">
    <input type="text" name="q" placeholder="Zoek restaurant">
    <button style='display:none;' type="submit">Zoek</button>
  </form>
</header>

<section id="restaurant-list">
  <ul>
    <% @restaurants.each do |restaurant| %>
      <li>
        <h3 class="name"><%= link_to restaurant.name, [@city, restaurant] %></h3>
        <hr><p><%= restaurant.city.name %></p>
      </li>
    <% end %>
  </ul>
</section>

<script>
  function render(data) {
    const $result = $('#restaurant-list ul');
    let liArray = [];
    for(let restaurant of data.restaurants) {
      liArray.push(`<li>
        <h3 class="name"><a href='${restaurant.url}'>${restaurant.name}</a></h3>
        <hr><p><a href="${restaurant.city.url}">${restaurant.city.name}</a></p>
      </li>`);

    }
    if(liArray.length > 0) {
      $result.html(liArray.join(''));
    } else {
      $result.html("<li class='not-found'>Geen restaurants gevonden</li>");
    }
  }

  $('form').submit(function(e) {
    let search = $(this).find('input').val();

    fetch(`/search/city_restaurants?q=${search}&id=<%= @city.id %>`)
    .then(status)
    .then(json)
    .then(render)
    .catch(function(error) {
      console.log('Request failed', error);
    });

    e.preventDefault();
  })
</script>