config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  devise_for :users, layout: 'admin'

  namespace :admin do
    root 'menu_type_searches#index', as: 'root'
    resources :menu_type_searches, :menus, :restaurants, :cities
  end

  get 'scrape', to: 'scrapers#scrape'

  get 'search(/:action)', controller: 'search', action: :action, as: "search"

  resources :cities, :only => [:index, :create, :new]

  resources :cities, :path => '', :except => [:index, :create, :new]
  resources :cities, :path => '', :only => [] do
    resources :restaurants, :path => '', :except => [:index]
    resources :restaurants, :path => '', :only => [] do
      resources :menus, :path => '', :except => [:index]
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  extend FriendlyId

  has_many :restaurants

  friendly_id :name, use: :slugged

  validates :name, presence: true, uniqueness: { case_sensitive: false }

end

app/models/dish.rb
class Dish < ApplicationRecord
  has_many :ingredients, dependent: :destroy
  belongs_to :menu

  validates :name, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :dish

  validates :name, presence: true
end

app/models/menu.rb
class Menu < ApplicationRecord
  extend FriendlyId

  before_save :default_values

  has_many :dishes, dependent: :destroy
  belongs_to :restaurant
  belongs_to :menu_type

  friendly_id :name, use: :scoped, scope: :restaurant

  validates :name, presence: true, uniqueness: { scope: :restaurant_id, case_sensitive: false }

  private

  def default_values
    self.menu_type_id ||= 1
  end
end

app/models/menu_type.rb
class MenuType < ApplicationRecord
  has_many :menus
end

app/models/menu_type_search.rb
class MenuTypeSearch < ApplicationRecord
  before_save :default_values

  belongs_to :menu_type

  def self.find_type(type)
    find_or_create_by(searchable: type.downcase).menu_type
  end

  private

  def default_values
    self.menu_type_id ||= 1
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  extend FriendlyId
  dragonfly_accessor :image do
    default 'app/assets/images/uurwerker.png'
  end

  has_many :menus, dependent: :destroy
  belongs_to :city

  friendly_id :name, use: :scoped, scope: :city

  validates :name, presence: true, uniqueness: { scope: :city_id, case_sensitive: false }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/menus_controller.rb
class Admin::MenusController < AdminController
  def index
    @menus = Menu.order(id: :asc).includes(:restaurant)
  end

  def show
    @menu = Menu.includes(dishes: :ingredients).friendly.find params[:id]
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  layout 'admin'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    admin_root_path
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all.includes(:restaurants)
  end

  def show
    @city = City.friendly.find(params[:id])
    @restaurants = @city.restaurants
  end

  private

  def clean_params
    params.require(:city).permit(:name)
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_restaurant, only: [:show]

  def show
    @menu = @restaurant.menus.friendly.find(params[:id])
    @dishes = @menu.dishes.order(id: :asc).includes(:ingredients).order('ingredients.id')
  end

  private

  def set_restaurant
    @restaurant = Restaurant.friendly.find(params[:restaurant_id])
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_city, only: [:show]

  def show
    @restaurant = @city.restaurants.friendly.find(params[:id])
    @menus = @restaurant.menus.order(id: :asc).includes(:menu_type)
  end

  private

  def set_city
    @city = City.friendly.find(params[:city_id])
  end

  def clean_params
    params.require(:restaurant).permit(:name)
  end
end

app/controllers/scrapers_controller.rb
class ScrapersController < ApplicationController

  def scrape
    render plain: 'hoi'
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def restaurants
    if clean_params[:q].empty?
      @restaurants = Restaurant.includes(:city).sample(50)
    else
      @restaurants = Restaurant.fuzzy_search(name: clean_params[:q]).includes(:city)
    end
  end

  def city_restaurants
    if clean_params[:q].empty?
      @restaurants = Restaurant.where(city_id: clean_params[:id]).includes(:city)
    else
      @restaurants = Restaurant.fuzzy_search(name: clean_params[:q]).where(city_id: clean_params[:id]).includes(:city)
    end
  end

  private

  def clean_params
    params.permit(
      q: Parameters.string,
      id: Parameters.integer
    )
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @restaurants = Restaurant.includes(:city).order("RANDOM()").limit(50)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/web_scraper_helper.rb
module WebScraperHelper
end

app/views/admin/menus/index.html.erb
<div class="page-header">
  <h1>Menu's</h1>
</div>

<table class="table table-striped table-hover table-cursor">
  <thead>
    <th>#</th>
    <th>Name</th>
    <th>Restaurant</th>
    <th>Slug</th>
  </thead>
  <tbody>
    <% @menus.each do |menu| %>
    <tr data-href="<%= url_for admin_menu_path(menu) %>">
      <td><%= menu.id %></td>
      <td><%= menu.name %></td>
      <td><%= menu.restaurant.name %></td>
      <td><%= menu.slug %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<script>
$('.table > tbody > tr').on('click', function() {
  document.location = $(this).data('href');
});
</script>

app/views/admin/menus/show.html.erb
<div class="page-header">
  <h1><%= @menu.name %></h1>
</div>

<table class="table table-striped">
  <thead>
    <th>#</th>
    <th>Name</th>
    <th>Ingredients</th>
  </thead>
  <tbody>
    <% @menu.dishes.each do |dish| %>
    <tr>
      <td><%= dish.id %></td>
      <td><%= dish.name %></td>
      <td><%= dish.ingredients.map(&:name).join(', ') %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/menus/show.html.erb
<header>
	<a href="<%= url_for([@restaurant.city, @restaurant]) %>" class="back">Back</a>
	<h1><%= @menu.name %></h1>
	<form id="search" action="" method="get">
    <div class="searchbox">
      <input class="full" type="text" name="search" placeholder="Search for &quot;gorgonzola&quot;">
			<button style="display:none;" id="searchbtn" type="submit">Zoeken</button>
    </div>
	</form>
</header>

<section id="food-menu">
	<ul>
		<li><h3 class="dish name">Loading dishes&hellip;</h3></li>
	</ul>
</section>

<script>
'use strict';

const $form = $("#search");
const $input = $(".searchbox input");
const $dishMenu = $('#food-menu ul');

function sortDishes(data) {
  const options = {
    shouldSort: true,
    threshold: 0.3,
    location: 0,
    distance: 100,
    maxPatternLength: 32,
    keys: [
      "name",
      "ingredients.name"
    ]
  };

  $form.on('keyup keydown', function(e) {
    const searchString = $input.val().trim();
    const result = (searchString == '') ? data : searchDish(data, searchString.split(' '), options);
    render(result);
  });

	$form.submit(function(e) {
		$input.blur();
		e.preventDefault();
	});

	render(data);
}

function searchDish(data, searchArray, options) {
  const fuse = new Fuse(data, options);
  const result = fuse.search(searchArray[0]);

  if(searchArray.length > 1) {
    return searchDish(result, searchArray.slice(1), options)
  }
  return result;
}

function render(data) {
  const liArray = makeList(data, []);

	if (liArray.length > 0) {
		$dishMenu.html(liArray.join(''));
	} else {
		$dishMenu.html("<li class='not-found'>Geen gerechten gevonden</li>");
	}
}

function makeList(data, array) {
	const [head, ...tail] = data;

	if(head) {
		const li =
		`<li>
		  <h3 class="dish name">${head.name}</h3><h3 class="dish price">&euro;${Number(head.price).toFixed(2)}</h3>
		  <hr><p>${head.ingredients.map(i => i.name).join(', ')}</p>
		</li>`;
		return makeList(tail, array.concat(li));
	} else {
		return array;
	}
}

fetch(`<%= url_for(:only_path => false) %>.json`)
.then(status)
.then(json)
.then(sortDishes)
.catch(function(error) {
  console.log('Request failed', error);
});

</script>