config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  devise_for :users, layout: 'admin'

  namespace :admin do
    root 'menu_type_searches#index', as: 'root'
    resources :menu_type_searches, :menus, :restaurants, :cities
  end

  get 'scrape', to: 'scrapers#scrape'

  get 'search(/:action)', controller: 'search', action: :action, as: "search"

  resources :cities, :only => [:index, :create, :new]

  resources :cities, :path => '', :except => [:index, :create, :new]
  resources :cities, :path => '', :only => [] do
    resources :restaurants, :path => '', :except => [:index]
    resources :restaurants, :path => '', :only => [] do
      resources :menus, :path => '', :except => [:index]
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  extend FriendlyId

  has_many :restaurants

  friendly_id :name, use: :slugged

  validates :name, presence: true, uniqueness: { case_sensitive: false }

end

app/models/dish.rb
class Dish < ApplicationRecord
  has_many :ingredients, dependent: :destroy
  belongs_to :menu

  validates :name, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :dish

  validates :name, presence: true
end

app/models/menu.rb
class Menu < ApplicationRecord
  extend FriendlyId

  before_save :default_values

  has_many :dishes, dependent: :destroy
  belongs_to :restaurant
  belongs_to :menu_type

  friendly_id :name, use: :scoped, scope: :restaurant

  validates :name, presence: true, uniqueness: { scope: :restaurant_id, case_sensitive: false }

  private

  def default_values
    self.menu_type_id ||= 1
  end
end

app/models/menu_type.rb
class MenuType < ApplicationRecord
  has_many :menus
end

app/models/menu_type_search.rb
class MenuTypeSearch < ApplicationRecord
  before_save :default_values

  belongs_to :menu_type

  def self.find_type(type)
    find_or_create_by(searchable: type.downcase).menu_type
  end

  private

  def default_values
    self.menu_type_id ||= 1
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  extend FriendlyId
  dragonfly_accessor :image do
    default 'app/assets/images/uurwerker.png'
  end

  has_many :menus, dependent: :destroy
  belongs_to :city

  friendly_id :name, use: :scoped, scope: :city

  validates :name, presence: true, uniqueness: { scope: :city_id, case_sensitive: false }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  layout 'admin'
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all.includes(:restaurants)
  end

  def show
    @city = City.friendly.find(params[:id])
    @restaurants = @city.restaurants
  end

  private

  def clean_params
    params.require(:city).permit(:name)
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_restaurant, only: [:show]

  def show
    @menu = @restaurant.menus.friendly.find(params[:id])
    @dishes = @menu.dishes.order(id: :asc).includes(:ingredients).order('ingredients.id')
  end

  private

  def set_restaurant
    @restaurant = Restaurant.friendly.find(params[:restaurant_id])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def restaurants
    if clean_params[:q].empty?
      @restaurants = Restaurant.includes(:city).sample(50)
    else
      @restaurants = Restaurant.fuzzy_search(name: clean_params[:q]).includes(:city)
    end
  end

  def city_restaurants
    if clean_params[:q].empty?
      @restaurants = Restaurant.where(city_id: clean_params[:id]).includes(:city)
    else
      @restaurants = Restaurant.fuzzy_search(name: clean_params[:q]).where(city_id: clean_params[:id]).includes(:city)
    end
  end

  private

  def clean_params
    params.permit(
      q: Parameters.string,
      id: Parameters.integer
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/web_scraper_helper.rb
module WebScraperHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Unem.co</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <!-- <link rel="apple-touch-icon" href="/custom_icon.png"> -->
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admin', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%= admin_root_url %>">Unem.co Admin</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'MenuTypeSearch', admin_menu_type_searches_path %></li>
            <li><%= link_to 'Cities', admin_cities_path %></li>
            <li><%= link_to 'Restaurants', admin_restaurants_path %></li>
            <li><%= link_to 'Menus', admin_menus_path %></li>
          </ul>
          <div class="navbar-right">
            <%= link_to 'Sign out', destroy_user_session_path, class: 'btn btn-default navbar-btn', data: {:confirm => 'Are you sure?'}, method: :delete %>
          </div>
        </div>
      </div>
    </nav>

    <div class="container">
      <% if notice %>
      <div class="alert alert-info alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= notice %>
      </div>
      <% end %>
      <% if alert %>
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= alert %>
      </div>
      <% end %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Unem.co</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <!-- <link rel="apple-touch-icon" href="/custom_icon.png"> -->
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fetch/2.0.1/fetch.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/2.5.0/fuse.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Unem.co</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <!-- <link rel="apple-touch-icon" href="/custom_icon.png"> -->
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admin', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="page-header">
        <h1>Unem.co</h1>
      </div>
      <% if notice %>
      <div class="alert alert-info alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= notice %>
      </div>
      <% end %>
      <% if alert %>
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= alert %>
      </div>
      <% end %>
      <%= yield %>
    </div>

  </body>
</html>